modLoader = "javafml"
loaderVersion = "[${forge_version},)"
issueTrackerURL = "https://github.com/Wagers-of-Industrial-Warfare/SuitableForCombat/issues"
license = "MIT License"

[[mods]]
modId = "suitableforcombat"
version = "${version}"
displayName = "Suitable For Combat"
authors = "rbasamoyai"
description = """An assortment of uniforms from the 1400s to the 1800s"""
logoFile = "icon.png"

[[dependencies.suitableforcombat]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.suitableforcombat]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"